### ISSUE TITLE
IBI logging: Save data to a separate text file

### ISSUE THREAD

**Issue by andershoegh** [med-material/TunnelGoalFittsTests#16]
For the IBI tracking it would be useful if it created a .txt file with only the IBI data. Currently the logger takes EDA, IBI and more and pushes them into a .csv file. If for a certain setting a single .txt file/csv file with one column of data (no header on this file) could be made, it would help the students with fewer data handlings points.

**Comment by bastianilso** [comment]
I discussed this with @hendrikknoche and my understanding was that the students should know how to copy the IBI column out of the CSV files by themselves (or we should just provide instructions for it).
(However, FYI if it is something we want in the future, I can do this fairly easily from code).

**Comment by andershoegh** [comment]
It is very much a nice-to-have feature. It can pretty easily be dealt with. It would mainly be to avoid problems with "should there be a header on this file when I import the file into Kubios" and removing 0's from the file etc. 
Definitely not a priority though.

**Comment by bastianilso** [comment]
Closing this, as we hope to have something nicer in place for next RTII :-)
