### ISSUE TITLE
Tunnel should not be limited horizontally

### ISSUE THREAD

**Issue by bastianilso** [med-material/TunnelGoalFittsTests#2]
Tunnels currently stretch to the edges of the screen, but should actually be limited horizontally.

**Comment by Adel-Akbi** [comment]
Hello @bastianilso !

When I was working on this issue 😄, I noticed that the application is not responsive, some values of UI (e.g : HorizontalLayout) are fixed manually, they are not controlled by the parent element. 

For example, when I was working on the screen of my PC and swing the application on the extended screen, all  positions changed, that confirm that it's not responsive... 😕 

I managed to limit the tunnel horizontally by adding some things like canvas ... 

![TheAdditionOfCanvas](https://user-images.githubusercontent.com/45661981/67840468-44855b80-faf6-11e9-8e0c-f96f55e9d538.PNG)

This Canvas is set on World Space mode to reference it to the size of the application :

![WordSpace](https://user-images.githubusercontent.com/45661981/67841054-8236b400-faf7-11e9-913d-6f4addfe2874.PNG)

In this Canvas, I also added a Panel (Horizontal Layout) and set : 

1. order in layer on (-1) to make it priority lower.

2. padding (top & bottom) on 2.

![SettingsOfCanvas](https://user-images.githubusercontent.com/45661981/67848262-9c2ac380-fb04-11e9-99ba-70b4808a7319.PNG)

And here, you can see the final result that is displayed when I hit on play mode ⏯ : 

![ScreenShotFinalResult](https://user-images.githubusercontent.com/45661981/67849180-68e93400-fb06-11e9-9a21-2afde09d1f5d.PNG)

**Comment by bastianilso** [comment]
Thanks for the work @Adel-Akbi 👍 

We may have talked past each other, when I explained what this issue is about.

![image](https://user-images.githubusercontent.com/3967945/67858883-94761980-fb1a-11e9-9b95-8b0439317e66.png)

Currently when you try the game in Tunnel Mode, the tunnel is limited **vertically**.
This means, that your cursor cannot move a lot in the y-axis, if it wants to be on the blue background.

What this issue is about, is to limit the Tunnel Mode **horizontally**. See screenshot below:
![image](https://user-images.githubusercontent.com/3967945/67859273-7a890680-fb1b-11e9-936e-1a63839d821e.png)

This means that your cursor cannot go all the way to the edge of the screen. 😄

@Adel-Akbi: As for your other changes to the Menu UI. We need to keep your work separate from each other. If you have UI improvements, please open a new issue and write your plan and suggestions. For this issue, please start from the latest version of this project, and aim to only solve what I described above. This will keep everything clean. 

The project was made for 16:9 screen resolution, so make sure your display settings uses this:
![image](https://user-images.githubusercontent.com/3967945/67859480-069b2e00-fb1c-11e9-8030-b908188dd14d.png)

**Comment by bastianilso** [comment]
After the conversation with @hendrikknoche it turns out, that we actually need to reverse this again. The tunnel should _not_ be limited horizontally, only vertically:
![image](https://user-images.githubusercontent.com/3967945/72238792-2e5c4700-35df-11ea-98f3-ae4dfa46bd3a.png)

However, the green bars should always be as long as the grey area - currently small blue gaps appear when re-sizing the tunnel.
