### ISSUE TITLE
[R Shiny] Create initial application for statistical analysis of Fitts Law.

### ISSUE THREAD

**Issue by bastianilso** [med-material/TunnelGoalFittsTests#20]
Once we are logging data to the database, we should have a nice way to perform statistical analysis of people's submitted data. An application should be developed using R Shiny which reads data from our database and creates a visualization of people's performance, like below.

![tunnel-goal-fiits-mockups](https://user-images.githubusercontent.com/3967945/61537304-1d1eed00-aa37-11e9-9aa4-04935f500acd.png)

An example R Shiny app can be downloaded here: [r-shiny-analysis-example.zip](https://github.com/med-material/TunnelGoalFittsTests/files/3696938/r-shiny-analysis-example.zip)

**Comment by Adel-Akbi** [comment]
@bastianilso The main structure and features are made for that first RShiny app on my repo named "RShinyApp" it left only some little modifications to do.
Now it's time to start working on the seconde version: issue #25🌾
