### ISSUE TITLE
Pause mode shouldn't be activated once the application is launched.

### ISSUE THREAD

**Issue by Adel-Akbi** [med-material/TunnelGoalFittsTests#22]
When the application is launched, the pause mode is activated automatically. There are some "error pause" that must be fixed to solve this issue.
![Capture](https://user-images.githubusercontent.com/45661981/68117253-1be9d100-fefd-11e9-8f4c-cc08e1b784db.PNG)

**Comment by Adel-Akbi** [comment]
@bastianilso This issue is already fixed after connecting the Arduino. Shall I close it ?

**Comment by bastianilso** [comment]
Yes, feel free to close it.  👍
