### ISSUE TITLE
The Arduino program doesn't work on Unity

### ISSUE THREAD

**Issue by Adel-Akbi** [med-material/TunnelGoalFittsTests#26]
The arduino program is working fine, but on Unity doesn't. The error message is : `Closing connection to Arduino, on port: \\.\COM X`

**Comment by Adel-Akbi** [comment]
@bastianilso The arduino is working fine on Unity, and the message : `Closing connection to Arduino, on port: \\.\COM X` is including on the code **ConnectToArduino.cs** on the `ConnectPressed` function. So, I guess is just a checking of the conection of the arduino and after close the checking 🦅 
Also, I asked Yann to help me  to fix the issue, he noticed that one wire wasn't connected to the Arduino... I think it's due to so.


![Hnet com-image](https://user-images.githubusercontent.com/45661981/70433237-77215d00-1a81-11ea-9f24-c98fbe3b2745.gif)

**Comment by bastianilso** [comment]
That's great, thanks for investigating this. I am closing this issue then. 🎸
