### ISSUE TITLE
Add Extra Field For The R Shiny App

### ISSUE THREAD

**Issue by Adel-Akbi** [med-material/TunnelGoalFittsTests#28]
@bastianilso  I've created a new field named "TestId"  in the DB which can allow us to get back the full periode including the date and the execution time. I think this way can be easier to use rather than use each field separately (Date-Time & SessionTime). 🐙 

![TestId](https://user-images.githubusercontent.com/45661981/71891997-28321a80-3148-11ea-91d0-8c8092ab45c0.PNG)

**Comment by bastianilso** [comment]
Sure. I think `TestId` can be  a confusing name for this field, I suggest to call it `DateTime` instead.

**Comment by Adel-Akbi** [comment]
> Sure. I think `TestId` can be a confusing name for this field, I suggest to call it `DateTime` instead.

@bastianilso  Done 💯
