### ISSUE TITLE
Identify size/distance units and make sure they are small and on the same space

### ISSUE THREAD

**Issue by hendrikknoche** [med-material/TunnelGoalFittsTests#44]
in case we want to evaluate the device human resolution we need to be to go down in size to pixel level (to make it really hard to hit/select the target).
This also relates to the issue #41 of making the size available through numbers.

**Comment by bastianilso** [comment]
Basically we are concerned that there is an inconsistency between size and distance, and that the units which size/distance are measured are not comparable. So this invalidates the existing data we have potentially. So when we try to get small size targets, we might want to simply re-interpret what the scale means - and ensure that the scale actually operates in a unit which makes sense across screen sizes (not just pixels,...- millimeters, perhaps? could be calculated if we know the screens size).

**Comment by bastianilso** [comment]
solved with latest commit bc7335603427452ddf857d14efde2bb6f1e37daa
