### ISSUE TITLE
distance and size parameter 

### ISSUE THREAD

**Issue by hendrikknoche** [med-material/TunnelGoalFittsTests#55]
using a combination of size 69 and distance 10 results in a negative ID (-2) (can fix on the Rshiny server) but need to make sure how distance and size relate.

**Comment by bastianilso** [comment]
ObjectDistanceCm is calculated from two items:
- We look at the render bounds of each object, and calculate the distance between them - we use the coordinates places closest towards the middle of the screen.
- We multiply the distance in px, with a "centimeters per pixel" value.
```
objectDistanceCm = objectDistanceScreen * centimetersPerPixel;
```

![image](https://user-images.githubusercontent.com/3967945/111993803-54e90c80-8b17-11eb-9bf1-6870580d8854.png)

Does your fix work Hendrik? I'm wondering why we would need to add the object's width. But maybe the variables I use above are not what they seem..

**Comment by bastianilso** [comment]
See also the function in L702 GameManager:
https://github.com/med-material/TunnelGoalFittsTests/blob/master/assets/Scripts/Managers/GameManager.cs#L702
