### ISSUE TITLE
granularity of distance/size sliders

### ISSUE THREAD

**Issue by hendrikknoche** [med-material/TunnelGoalFittsTests#61]
it seems that the sliders only update the size and distances at multiples of 4.
Fitts (distance in steps of 2 only)
Tunnel (size 4, distance 2)
Goal (distance 2)

**Comment by bastianilso** [comment]
![size-distance gif](https://user-images.githubusercontent.com/3967945/157232289-d9f586c5-1bc6-4911-a1ff-694556d62ed6.gif)

The above animation show what is supposed to be the current behavior.

The last time the behavior was touched, we changed the mapping of the sliders from a linear mapping to a power function
(commit e0b285cb2418f43b8e83571c072172b1b611f775). The reason being that we could not achieve the size of 1 pixel with a normal linear mapping. so the mapping is now nonlinear.

**Comment by bastianilso** [comment]
We agree it would be useful to:

- Have the size and distance parameters represented in centimeters, based on what is written in "Screen width" and "Screen height".
- That the distance slider should move on every step - it seems that it moves on every 2nd step right now.

**Comment by bastianilso** [comment]
need to test:
 - if they set some size and some distance and they use the formula for the course for ID, (ID equals log 2 ...).
 - then the data get send to the server and we have something that calculates that. And that should be matching with what they could calculate themselves.
 - And we need to identify any issues/mistakes, and verify pipeline.
 - `Numbers of sliders == numbers sent to database == numbers retreived in R Shiny app == R shiny calculation.`

**Comment by bastianilso** [comment]
First issue  fixed in 57314f9ca534cc7d724989bfbfa40ba0e13d73fb and now displaying it as centerimeters  04c03a9a006aca2e06512ced04346ca8bad78c22

The wrongly calculated FittsID is now handled in this issue (seems to be R shiny issue?)
https://github.com/med-material/TunnelGoalFittsRShiny/issues/9
